# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: React elastic dnd dev

on:
   pull_request:
    types: closed
    branches:
      - dev

jobs:
  build:  
    runs-on: [self-hosted,dev]
    
    strategy:
     matrix:
      node-version: [16]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test